CREATE TABLE carona(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    origem VARCHAR(255) NOT NULL,
    destino VARCHAR(255) NOT NULL,
    horario_saida TIMESTAMP NOT NULL,
    vagas_totais INT NOT NULL,
    vagas_disponiveis INT NOT NULL,
    status_viagem VARCHAR(9) NOT NULL CHECK (status_viagem IN ('CRIADA', 'CHEIA', 'CONCLUIDA', 'CANCELADA')),
    user_id BIGINT NOT NULL,
    veiculo_id BIGINT NOT NULL,

    CONSTRAINT fk_veiculo FOREIGN KEY (veiculo_id) REFERENCES veiculo(id),
    CONSTRAINT fk_users FOREIGN KEY (user_id) REFERENCES users(id)
)