CREATE TABLE mensagem(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    texto VARCHAR(255) NOT NULL,
    data_envio TIMESTAMP NOT NULL,
    carona_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,

    CONSTRAINT fk_carona FOREIGN KEY (carona_id) REFERENCES carona(id),
    CONSTRAINT fk_users FOREIGN KEY (user_id) REFERENCES users(id)
);